name: edgefusion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  google_fonts: ^4.0.4
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  http: ^0.13.3
  flutter_image_compress: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
